# Generated by Django 3.0.8 on 2021-03-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_sent',
        ),
    ]
