# Generated by Django 3.0.8 on 2021-03-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_send',
        ),
    ]
